overlay : BBBIO-EHRPWM-00A0.dtbo
	sudo -s cp BBBIO-EHRPWM-00A0.dtbo /lib/firmware/
	sudo sh -c 'echo BBBIO-EHRPWM >> /sys/devices/bone_capemgr.9/slots'

view :
	sudo cat /sys/devices/bone_capemgr.9/slots 
